- android/src/main/java/com/reactnativecommunity/netinfo/NetInfoModule.java
- ios/RNCNetInfo.m
- js/index.js
Removed the code which was deprecated in July 2017 (https://github.com/react-native-community/react-native-netinfo/commit/47b927830b7aa24d9ded025bd030b44e2624d003).
> chore: Remove deprecated code

- .circleci/config.yml
- .releaserc
- package.json
- yarn.lock
This PR adds semantic-release to this repo.
> chore(tooling): added semantic release

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/question.md
- .github/PULL_REQUEST_TEMPLATE.md
They are based on the issue templates from [react-native-cli](https://github.com/react-native-community/react-native-cli/tree/27d4924a582ef610bed901a048ee2258c779ebd5/.github).
*The tests will not run on this PR as I have marked this commit as [skip ci] to avoid using our CircleCI budget.*
> docs: Add issue and pull request templates

- example/ios/NetInfoExample-tvOS-Info.plist
- example/ios/NetInfoExample.xcodeproj/project.pbxproj
- example/ios/NetInfoExample.xcodeproj/xcshareddata/xcschemes/NetInfoExample-tvOS.xcscheme
- example/ios/NetInfoExample/Base.lproj/LaunchScreen.xib
- example/ios/NetInfoExample/Images.xcassets/AppIcon.appiconset/Contents.json
- ios/RNCNetInfo.xcodeproj/project.pbxproj
- ios/RNCNetInfo.xcodeproj/xcshareddata/xcschemes/RNCNetInfo-tvOS.xcscheme
Added RNCNetInfo-tvOS target so the library now works also on tvOS like before.
> Add support for tvOS

- .github/ISSUE_TEMPLATE/bug_report.md
Just fixing a typo at `bug_report.md` description.
No needed, since it is just related to an issue template file.
> fix(bug_report): typo on description

- package.json
I'd love to use this repo with 59.1  This PR allows for this.
Simply run net-info on 59.1.
> Allow users of 59.1 to use netinfo

- README.md
Updated the style of the documentation to make usage and the API much clearer.
Not required.
[ci skip]
> docs: Make the README documentation much clearer

- typings/index.d.ts
Fix the TS declarations as per report from @minhloi.
@minhloi Can you check that this is now correct?
> fix: Ensure the Typescript declaration has no errors

- README.md
> Corrected the android package name

- typings/index.d.ts
Hello !
I tried to use this package in a typescript project and types are not consistent with the documentation.
I updated types according the documentation and code.
Cheers,
Dimitri
> update typing to be coherent with documentation

- package.json
> fix(types): generates index.d.ts instead of using index.ts directly

- android/src/main/java/com/reactnativecommunity/netinfo/NetInfoModule.java
Add `@ReactModule` annotation, this will eventually be used by TurboModules annotation processor.
Trivial, test that it builds.
> Add `@ReactModule` annotation

- README.md
Following current docs gives error 'TypeError: Cannot read property 'then' of undefined'
> docs: Update docs regarding jest

- README.md
add the conversion to string in order to get the value displayed in the React component
> [docs] fix the README

- ios/RNCConnectionState.h
- ios/RNCConnectionState.m
- ios/RNCNetInfo.m
> Detect wired connection and retrieve the wifi IP address (and subnet) on Apple TVs

- README.md
Detected `YourComplement` typo while reading the docs: https://github.com/react-native-community/react-native-netinfo/blob/master/README.md#usenetinfo
No need of tests.
> Fixed Component typo

- README.md
- ios/RNCNetInfo.m
I've added in the `ssid` key to the details object on WiFi connection on iOS.
I couldn't test the code on a real iPhone, I do not have access to one at the moment.
> feat: iOS SSID to WiFi details

- package.json
Quick follow-up to 1c2de779f6341a705f8606d0ba4297c229fcc262
@matt-oakes
> Remove reference to spotless

- CHANGELOG.md
@matt-oakes I think you meant to say what my patch makes it say?
Congrats on v5 :-)
> docs(CHANGELOG): fix grammar on deprecated removal

- README.md
- android/src/main/java/com/reactnativecommunity/netinfo/ConnectivityReceiver.java
Only added the information if wifi of the device is on or off. Sometimes you are not connected to a network but the wifi is on, you couldn't check that before.
Tested on an Android device with Android 9.0, it functions as it should
> [feat] Information about whether the wifi is On or Off

- README.md
- jest.setup.js
- jest/netinfo-mock.js
- package.json
Closes #188 
Included `jest.setup.js` as one of the files included when downloading this package, and exported the mock contents.
yarn test
> Export RNCInfo mock file

- src/internal/defaultConfiguration.web.ts
Changes for the web had been omitted from previous commit(4e3e981) 
None
> fix: Make the default timeouts for web correct

- package.json
> fix(macos): Ensure macOS files are included in the NPM package

- android/src/main/java/com/reactnativecommunity/netinfo/ConnectivityReceiver.java
- android/src/main/java/com/reactnativecommunity/netinfo/NetworkCallbackConnectivityReceiver.java
Some of the code in `NetworkCallbackConnectivityReceiver.java` was not indented in standard Java style. I ran the Android Studio "Reformat Code" over the package, and applied a couple changes to make it more idiomatic Java.
These changes do not affect the Java byte code.
> style: Fix code formatting using Android Studio

- src/internal/nativeModule.web.ts
- src/internal/types.ts
Added missing wifi property strength to the typescript
> fix: added strength wifi property to typescript

- src/index.ts
self-explanatory commit + PR title :-)
> docs: typo in docs for return value of addEventListener

- ios/RNCNetInfo.m
Fixes https://github.com/react-native-netinfo/react-native-netinfo/issues/492
> Remove methods that break event listeners on RN 0.65.1

- example/ConnectionInfoCurrent.tsx
- example/ConnectionInfoFetch.tsx
- example/ConnectionInfoSubscription.tsx
- example/IsConnected.tsx
- example/NetInfoHook.tsx
- example/index.tsx
without this, on my machines at least (dark mode perhaps?) the example
did not show up any results - it was all blank
Related #532 /  #521
Tested on android, ios and windows
> test(example, windows): fix windows example white-on-white text

- README.md
Add tips in Readme/Troubleshooting about a work around for switching between different Wi-Fi networks in iOS when app was in background.
N/A
> Pull request readme add new troubleshooting

- README.md
Fixes https://github.com/react-native-netinfo/react-native-netinfo/issues/543
Added 5G network type to README file
> docs(README): document new 5G network types

- README.md
Just add the support for web in the readme file in some places where it was missing.
Fixes #485
> Add web support in the Readme

- src/internal/nativeModule.web.ts
Fix web module issue when removeListeners
> fix: web module removeListeners

- README.md
- android/src/main/java/com/reactnativecommunity/netinfo/ConnectivityReceiver.java
- src/internal/nativeModule.web.ts
- src/internal/types.ts
…droid. (#604)
close ( #604 )
This will add linkSpeed, rxLinkSpeed, txLinkSpeed to the details, when wifi and android platform.
Run example on Real Device
> feat: add linkSpeed, rxLinkSpeed, txLinkSpeed info to wifi on android

- android/src/main/java/com/reactnativecommunity/netinfo/NetworkCallbackConnectivityReceiver.java
> fix: falsey vpn issue #460

- src/internal/types.ts
Fixes #693 - should have been caught in CI with type checking but somehow was not, separate issue
Recommended typing from @idrissakhi - user confirms it works for them
> fix(types): fix type error on new headers feature

- src/internal/types.ts
This is a small fix that I identified when I was trying to mock the library at my jest + typescript tests.
All checks still working as expected.
Hope it can be useful for everyone.
> fix(types): isConnected / isInternetReachable should be `boolean` not `true`
