react-native-netinfo/react-native-netinfo

js/index.js
package.json
typings/index.d.ts

I have simplified the Flow types to remove the use of `$Enum`, which is undocumented in the Flow documentation and replaced them with simple type definitions. This also removed the confusion over if it's `cell` or `cellular` as the enum used different values for the key and value (It turns out that the `@types/react-native` types are actually wrong and it's `cellular`).
I have also added TypeScript typings to the repository which should make it seamless to get type support for either language.

Flow & TypeScript Typings

---

.circleci/config.yml
.gitignore
jest.setup.js
js/__tests__/eventListenerCallbacks.js
js/__tests__/eventListenerManagement.js
js/__tests__/getConnectionInfo.js
js/__tests__/isConnected.js
js/__tests__/isConnectionExpensiveAndroid.js
js/__tests__/isConnectionExpensiveIOS.js
js/index.js
js/nativeInterface.js
package.json

This adds tests for the Javascript code using Jest. It tests 100% of the JS code by mocking the native module interface.
To make this easier it adds a helper class which exposes the native module and the native event emitter. This is based off a pattern from the [`NativeAnimatedHelper.js`](https://github.com/facebook/react-native/blob/1151c096dab17e5d9a6ac05b61aacecd4305f3db/Libraries/Animated/src/NativeAnimatedHelper.js) file in the React Native Core and makes it very easy to simulate events being emitted.

Jest Tests

---

android/src/main/java/com/reactnativecommunity/netinfo/BroadcastReceiverConnectivityReceiver.java
android/src/main/java/com/reactnativecommunity/netinfo/ConnectivityReceiver.java
android/src/main/java/com/reactnativecommunity/netinfo/NetInfoModule.java
android/src/main/java/com/reactnativecommunity/netinfo/NetworkCallbackConnectivityReceiver.java

*Migrated from https://github.com/facebook/react-native/pull/22981*
This PR changes NetInfo to use the newer and better supported [NetworkCallback](https://developer.android.com/reference/android/net/ConnectivityManager.NetworkCallback) on API levels 24 and above.
This is in place of the now deprecated BroadcastReceiver method. Both are kept so we can continue supporting down to API level 16. This is done by splitting out the connectivity code into two different classes, organised around a base abstract class to avoid duplication. Which class to use is chosen at runtime with a simple `if` statement in the NetInfo module.
The structure of the `connectionChange` event has not been changed, so this will be a non-breaking change for most users. The slight exception to that is that I have now …

feature: Use the newer NetworkCallback API on versions of Android which support it

---

README.md
react-native-netinfo.podspec

Adds the podspec which is is required to use the library with Cocoapods. I have also added the instructions to the README.

feat(linking): Add Cocoapods Podspec

---

example/e2e/sanityTest.spec.js
example/e2e/testCases/multipleIsConnected.spec.js
example/index.js
example/testCases/MultipleIsConnected.js
example/testCases/index.js
ios/RNCNetInfo.m
ios/RNCNetInfo.xcodeproj/project.pbxproj

This fixes the issue where multiple calls to `isConnected.fetch` would only resolve the final one on iOS. It would correctly resolve them on Android.
The fix was was keep a copy of all of the resolvers, not just the last one, in an NSSet. We can then call them all when the connection data comes back.
I have also added an e2e test case to test this behaviour. We need to wait for #14 to be merged in before this is ready to do. I'm opening a fancy new "draft" PR now so it's here.
Fixes #10.

fix(iOS): Ensure all calls to isConnected.fetch resolve

---

README.md

Just a small change to the readme to add Contributing & License links.

docs: add contributing guide link to readme

---

README.md
react-native-netinfo.podspec

In order to fix the error and the warn above, this PR:
1. changes `s.name` from `@react-native-community/netinfo` to `react-native-netinfo`
2. adds a `:tag` to `s.source`
Install `react-native-netinfo` on iOS using CocoaPods 😅

fix(podspec): remove slash from "name" and add missing ":tag"

---

typings/index.d.ts

This PR fixes TypeScript support by correctly exporting the methods as the default export.
Use the library in a TypeScript file and see that the types work correctly.
Before:
After:

fix(typing): Correctly export the methods for TypeScript

---

example/android/app/build.gradle

The Android tests were failing on CircleCI. This looks to be an actual issue with the tests when running in release mode. The Javascript bundle was not being created correctly in the release APK. This PR should fix the issue and the ones in #23.
CircleCI tests should pass.
Closes: #26

test(android): Ensure the release verison of the app has the Javascript correctly bundled

---

js/nativeInterface.js

Shows a helpful error message if linking has not been done correctly and the native module is null. It gives the steps that are most likely to fix the issue.
Before:
After:
This will help to diagnose linking issues like #30.
Delete `RNCNetInfo.a` from the "Linked Frameworks and Libraries" section and see the new error message.

Throw an error if the native module is null with steps to help fix the issue

---

.circleci/config.yml
README.md
example/android/app/build.gradle
example/android/app/src/androidTest/java/com/reactnativecommunity/netinfo/example/DetoxTest.java
example/e2e/testCases/emitOnListen.spec.js
example/testCases/EmitOnListen.js
example/testCases/index.js
js/__tests__/eventListenerCallbacks.js
js/__tests__/eventListenerManagement.js
js/__tests__/isConnected.js
js/index.js
package.json
yarn.lock

This PR changes the way that the library handles event subscriptions. Previously, each listener was hooked directly to the `DeviceEventEmitter` via a "handler" which transformed the shape of the returned object. This worked well, but exposed some platform differences as reported in #8.
This PR changes the system so the library will manage a single subscription to the `DeviceEventEmitter` and call all of the subscribed listeners when it reports changes. This also allows us to keep track of the latest information and call new listeners with it right away on both platforms. If the library has not yet received any information from the native code, it will request it and send it to the new listeners.
Even through this requires no code changes for users and they should not have been making …

Change how event listeners work

---

.github/ISSUE_TEMPLATE/bug_report.md
README.md

There is a [known](http://openradar.appspot.com/14585459) [issue](http://www.openradar.appspot.com/29913522) with the iOS Simulator, as reported in #7. As this is an Apple issue which there is no clean workaround, and it's only for the development environment, I have listed it as a known issue in the README. I have also added a note to the bug report template to make it clear that iOS issues need to related to a real device to avoid issues being opened in the future.

docs: Document the known issues with the iOS Simulator

---

android/src/main/java/com/reactnativecommunity/netinfo/ConnectivityReceiver.java
ios/RNCNetInfo.m
js/__tests__/eventListenerCallbacks.js
js/__tests__/eventListenerManagement.js
js/__tests__/getConnectionInfo.js
js/__tests__/isConnected.js
js/index.js
js/nativeInterface.js
js/types.js
package.json
typings/index.d.ts

Based on the comments from @EvanBacon I have:
* Changed the native code to have the same object shape as we send out from Javascript. This eliminates the need for the transformation.
* Improved the flow type coverage. Unfortunately, we need to ignore one error as we can't use the expected type directly from `react-native`. I have added a comment on this case.
* Removed the `fetch()` method from the TypeScript types as this method was removed after being deprecated for years.
CircleCI should pass still.

Unify the object shapes and improve type coverage

---

android/src/main/java/com/reactnativecommunity/netinfo/NetworkCallbackConnectivityReceiver.java

Fixes #57.
The issue was caused by a difference in the order that `ConnectivityManager.NetworkCallback` methods are called on that Android version. We now ensure that we always have the correct information to get the network state, regardless of which callback is called when.
* CircleCI should still pass.
* Users can test this on their devices by installing this branch using this command:
`yarn add @react-native-community/netinfo@react-native-community/react-native-netinfo#matt-oakes/issue-57`

fix: Issue with getting the network state on Android 7.0+ devices

---

android/src/main/java/com/reactnativecommunity/netinfo/NetInfoModule.java

This PR fixes #32.
It does this by ensuring the network information is kept up-to-date when the app goes into the background.
Tested against https://github.com/matt-oakes/net-info-test and ensured that the tests in this repo still pass.
---
@filippoitaliano @ersel You can install this version by running this command and rebuilding your app. Can you test to check that it fixes the issue for you:
`yarn add '@react-native-community/netinfo@react-native-community/react-native-netinfo#@matt-oakes/issue-32'`
(not a confusing command at all... :wink:)

fix: Ensure Android network information is correct when the app returns from the background

---

android/src/main/java/com/reactnativecommunity/netinfo/ConnectivityReceiver.java

I've seen the following crash, which seems to be limited to Huawei devices:
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.net.NetworkInfo.getSubtype()' on a null object reference
at com.reactnativecommunity.netinfo.ConnectivityReceiver.register(ConnectivityReceiver.java:94)
at com.reactnativecommunity.netinfo.ConnectivityReceiver.getEffectiveConnectionType(ConnectivityReceiver.java:94)
at com.reactnativecommunity.netinfo.NetworkCallbackConnectivityReceiver.updateAndSend(NetworkCallbackConnectivityReceiver.java:66)
at com.reactnativecommunity.netinfo.NetworkCallbackConnectivityReceiver.access$102(NetworkCallbackConnectivityReceiver.java:24)
at com.reactnativecommunity.netinfo.NetworkCallbackConnectivityReceiver$ConnectivityNetworkCallback …
```

NetworkInfo is null on Huawei devices

---

.circleci/config.yml

This changes CircleCI to use the newly published version of the Orb.
CircleCI tests should pass 🌈

chore(ci): Change to the released version of the React Native CircleCI Orb

---

android/src/main/java/com/reactnativecommunity/netinfo/NetworkCallbackConnectivityReceiver.java

Fixes the issue outlined in #44. With this change it is now possible to receive a "none" connection type and actually know when there is no connection available.
Tested on device with various combinations of airplane mode, wifi state, cellular radio, and VPN.
Closes #44.

Fix: Properly report lost connection as 'none' on Android 24+ (#44)

---

typings/index.d.ts

Corrects the Typescript type definitions for users who do not have `esModuleInterop` turned on.
Supersedes #69.
Tested on a Typescript project with the option on and off.

Correct the Typescript type definitions

---

typings/index.d.ts

Hi,
I noticed that #82 missed a couple uses of deprecated types which were causing issues if you're using the NetInfoData interface.

fix: Remove uses of deprecated types

---

android/src/main/java/com/reactnativecommunity/netinfo/NetworkCallbackConnectivityReceiver.java

We've seen a couple crashes on various Android API 24+ devices when this unregister network call is made. I don't have repro steps but have included an example stack trace showing where it originates during Activity.onPause calls.
Caused by java.lang.IllegalArgumentException: Invalid NetworkCallback
at android.net.ConnectivityManager.unregisterNetworkCallback(ConnectivityManager.java:3593)
at com.reactnativecommunity.netinfo.NetworkCallbackConnectivityReceiver.unregister(NetworkCallbackConnectivityReceiver.java:47)
at com.reactnativecommunity.netinfo.NetInfoModule.onHostPause(NetInfoModule.java:43)
at com.facebook.react.bridge.ReactContext.onHostPause(ReactContext.java:221)
at com.facebook.react.ReactInstanceManager.moveToBeforeResumeLifecycleState(ReactInstanceManager.java:673)
at …

Add defensive catch when unregistering network

---

android/src/main/java/com/reactnativecommunity/netinfo/NetworkCallbackConnectivityReceiver.java

If a subscription to the network state was made on Android N+ when there was no active network, none of the callbacks would get called. Therefore, the state would be incorrectly reported as "unknown".
This PR adds a check if no active network on register and then manually calls `updateAndSend()` to emit the `none` state.
Fixes #77
Tested on a Pixel 2 in various states.

fix(Android): Send a "none" status if the device has no active network on launch

---

README.md
android/src/main/java/com/reactnativecommunity/netinfo/BroadcastReceiverConnectivityReceiver.java
android/src/main/java/com/reactnativecommunity/netinfo/ConnectivityReceiver.java
android/src/main/java/com/reactnativecommunity/netinfo/NetworkCallbackConnectivityReceiver.java
src/internal/__tests__/deprecatedUtils.ts
src/internal/deprecatedUtils.ts
src/internal/types.ts

Adds the ability to detch VPN connections on Android. These were previously reported as "unknown". I have also added a fallback to "other" if we have a connection, but can't determine the type. This means we can handle new types being added without the user being reported incorrectly as "offline".
Fixes #87.
Tested on multiple Android devices with a VPN client.

feat(Android): Detect and report VPN connections correctly on Android

---

README.md
src/internal/nativeInterface.ts

Adds instructions for getting the module to work correctly with Jest.
Currently the suggested mock is just enough to get the library running. In the future we can add a better mock which can be used to actually control and mock network conditions.
Fixes #75

docs: Add instructions for integrating with Jest unit tests

---

src/internal/deprecatedSubscriptions.ts
src/internal/subscriptions.ts
tsconfig.json

This is a simple fix for #100 which removed the need for `es6` or the downlevel-iterators TypeScript flag.
Fixes #100.
Tests should pass.
cc @mikehardy

Do not require es6 or downlevel-iterators TS flag

---

README.md
package.json
windows/.gitignore
windows/RNCNetInfo.sln
windows/RNCNetInfo/DefaultNetworkInformation.cs
windows/RNCNetInfo/IConnectionProfile.cs
windows/RNCNetInfo/INetworkInformation.cs
windows/RNCNetInfo/Properties/AssemblyInfo.cs
windows/RNCNetInfo/Properties/RNCNetInfo.rd.xml
windows/RNCNetInfo/RNCNetInfo.csproj
windows/RNCNetInfo/RNCNetInfoModule.cs
windows/RNCNetInfo/RNCNetInfoPackage.cs

This PR adds Windows as a supported platform.
I started by bringing over the code from the [react-native-windows](https://github.com/microsoft/react-native-windows/tree/0.57-stable/ReactWindows/ReactNative/Modules/NetInfo) repo and then I implemented the new features that have been added to this repo since it was extracted from the core of React Native.
I tested this PR manually by adding it to the [ReactXP Sample Project](https://github.com/microsoft/reactxp/tree/master/samples/RXPTest) and combining it with a WIP PR I currently have open at https://github.com/microsoft/reactxp/pull/1092
I have not added any automated tests with this PR because I have struggled to get this repo's automated tests to run on Windows.

feat(windows): Add Windows as a supported platform

---

README.md

It looks like the guide for what to mock in jest didn't get updated when the new V3 of the API landed. I've updated the `README.md`, according to the types in [src/internal/privateTypes.ts](https://github.com/react-native-community/react-native-netinfo/blob/master/src/internal/privateTypes.ts).
Let me know if it is not correct, or if there's anything else I need to change.

Update jest mock guide to match V3 API

---

android/src/main/java/com/reactnativecommunity/netinfo/ConnectivityReceiver.java

Fixes a crash when trying to access a `null` cellular generation value:
```
Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'java.lang.String com.reactnativecommunity.netinfo.types.CellularGeneration.label' on a null object reference
```

Add a null check for mCellularGeneration to avoid a potential crash

---

ios/RNCConnectionStateWatcher.m

At Mattermost we received a lot of reports about Internet Reachability not working on LTE networks that assign IPv6 addresses, the current implementation uses a hostname based to test for reachability and the hostname "apple.com" does not have IPv6 addresses causing the check to fail.
With this PR we implemented the Internet connectivity test exposed in [this example](https://developer.apple.com/library/archive/samplecode/Reachability/Listings/ReadMe_md.html#//apple_ref/doc/uid/DTS40007324-ReadMe_md-DontLinkElementID_11)
it uses a different mechanism.
```
- reachabilityWithHostName and SCNetworkReachabilityCreateWithName:  Internally, this API works be resolving the host name to a set of IP addresses (this can be any combination of IPv4 and IPv6 addresses) and establishing separate …
```

Support IPv4/6 on iOS

---

react-native-netinfo.podspec

After upgrading my tvOS project to RN 0.60+, I found the new pod auto-linking feature wasn't working for react-native-netinfo on tvOS due to support not being specified for tvOS. Adding this to the podspec allows `pod install` to work correctly for tvOS.
Try and use react-native-netinfo in a tvOS project on RN 0.60+. Note that `pod install` will throw an error (tvOS not supported). Update the podspec as per this PR and try again and it will work.
Note that my project uses [react-native-offline](https://github.com/rgommezz/react-native-offline) which uses react-native-netinfo which just switched over to community react-native-netinfo ([link](https://github.com/rgommezz/react-native-offline/pull/204)).

Add tvOS to podspec supported platforms

---

react-native-netinfo.podspec

CocoaPods will fail if `react-native-netinfo` is imported using `:podspec`:
```ruby
pod 'react-native-netinfo', :podspec => 'node_modules/@react-native-community/netinfo/react-native-netinfo.podspec'
```
Modify `Podfile` to use `:podspec` instead of `:path`, then make sure `pod install` succeeds.

fix(iOS): correct tag so CocoaPods can clone the repo

---

.npmignore

Removes the `examples` folder from the NPM package.
Fixes #175

fix: Do not include examples in the NPM package

---

ios/RNCNetInfo.m

0aa2486cc55503d9ff4c30a099285188307e36e0 missed a tvOS check, this PR fixes that
Build for tvOS

fix(tvOS): Do not import CoreTelephony on tvOS

---

README.md
android/build.gradle
android/gradle.properties
example/android/app/build.gradle
example/android/build.gradle
example/android/gradle.properties

The idea with this PR is to remove breaking changes supporting AndroidX, as we can see here: https://github.com/react-native-community/react-native-netinfo/issues/191
Please let me know the **commands** to verify these changes from Android 👍 
If you want I can modify the README to include the instructions :)

Add gradle backward-compatibility with AndroidX

---

README.md
android/src/main/java/com/reactnativecommunity/netinfo/ConnectivityReceiver.java
ios/RNCNetInfo.m

I've added in the **subnet mask** to the `details` object on WiFi connection both on Android and iOS.
Screenshot:

feat: Added 'subnet' to wifi details [Android & iOS]

---

ios/RNCConnectionStateWatcher.m

When React Native is invalidated on a background thread, we can get
a use-after-free crash because RNCConnectionStateWatcher may be
deallocated while the callback is called.
Addresses #206.
This is a bit hard to test since it involves setting up the right conditions for
this to trigger. I'm open to any suggestions here.

fix(iOS): race condition when releasing resources

---

ios/RNCConnectionState.h

Removes an unused method with missing definition.
iOS compilation should not fail.

fix(iOS): Method definition for 'dictionaryValue' not found

---

android/build.gradle

`build.gradle` was missing a maven reference to correctly resolve the locally installed `react-native` dependency. This had the effect that it would resolve version `0.20.1` from [Maven Central](https://mvnrepository.com/artifact/com.facebook.react/react-native) (the last version published in Feb 2016).
Also, `react-native` was incorrectly declared as an `api`-type dependency - That is not required. Using a regular `implementation`-type dependency should be enough, which is used by other RN library projects as well. App projects contain their own reference for `react-native`.
Fixes #214
Closes #215
1. Clone project
2. `cd android`
3. `gradlew build`
EDIT:
Instead of building from command line, the same issue can be seen by just opening the `android` folder with **Android Studio**. …

Fix build.gradle react-native dependency

---

README.md
ios/RNCNetInfo.m

fix(iOS): CNCopySupportedInterfaces() isn't supported on tvOS (#258)

---

android/src/main/java/com/reactnativecommunity/netinfo/AmazonFireDeviceConnectivityPoller.java
android/src/main/java/com/reactnativecommunity/netinfo/ConnectivityReceiver.java
android/src/main/java/com/reactnativecommunity/netinfo/NetInfoModule.java

Looks like FireOS does not correctly report capabilities of the default network correctly, reporting a validated state when the internet is not actually reachable. After much experimentation on our project we were able to nail down the actions and broadcasts the OS uses to perform connectivity checks. While these are undocumented by Amazon, they have been in wide use for a while and have been presented as a side note in some presentation slides from Amazon.
This implementation will detect if the device in use is a FireOS device and only enable the extra checks if so. The data received from FireOS will override the mIsInternetReachable in ConnectivityReceiver instead of replacing it, allowing for other overrides to be done in a similar way later on for other platforms that do not use …

[feat/fix] Add ability to detect network reachability on FireOS devices

---

android/build.gradle

I followed the instructions of README that suggest to define a value to `androidXCore`. But when it's defined together with `supportLibVersion`, the conditional doesn't match to use the androidx.
I know that this sounds weird to use both definitions together, but this is the only solution as I'm using [@react-native-community/react-native-maps with androidx](https://github.com/react-native-community/react-native-maps/blob/master/lib/android/build.gradle#L20-L22) in my project.
For now, I resolved using the undocumented definition of `androidXVersion`, but it'll be good to have both setup options as it's kinda of a simple solution.
1 - Change the `android/build.gradle`
```groovy
buildscript {
ext {
buildToolsVersion = "28.0.3"
minSdkVersion = 16
compileSdkVersion = 28
targetSdkVersion = 28 …
```

Use androidXCore together with supportLibVersion

---

ios/RNCNetInfo.m

Preventing build failure by adding conditions to exclude `ssid` from being used on tvOS builds.

fix: adding conditions to exclude ssid from being used on tvOS

---

android/src/main/java/com/reactnativecommunity/netinfo/NetworkCallbackConnectivityReceiver.java

This fixes #285 - a null pointer possible in the recent fix for cell->airplane connectivity handling in Android, PR #265 from @lfalkner 
That PR is great but there appears to be a subtle interaction between the older deprecated synchronous APIs in combo with the async connection change listener
The API that returns an unexpected null to the code in #265 is part of the fallback code, and it's deprecated because according to the [Android API docs the synchronous ConnectionManager APIs don't operate in order and thus state might be incoherent (!?)](https://developer.android.com/reference/android/net/NetworkInfo.html) while the arguments provided in the callback methods (which is the main codepath in #265) are asserted to be coherent and so wouldn't suffer this.
So I'm guessing that on lower …

fix(android): Handle invalid networks in network listener

---

src/index.ts

This corrects the reachability timeouts being swapped in the default configuration, thereby causing reachability checks to be repeated every 5 seconds if the previous reachability status was good and only every 60 seconds, otherwise.
No issues were reported by ESLint and Jest.

fix: Correct reachability timeouts in default configuration

---

README.md
src/index.ts
src/internal/internetReachability.ts
src/internal/types.ts

This fixes an issue where a reachability check would not produce a result until a response from the reachability request is received. The fetch API, which is used for this purpose, does not have a built-in timeout mechanism, therefore requests can, in theory, stay pending forever. In case of a bad connection with packet loss, this can mean that no reachability issues are detected, even though there is effectively no internet connection. This commit aims to fix this issue by implementing a user-configurable request timeout.
One side-effect of the changes is that canceling a pending reachability check (see `InternetReachability_checkInternetReachability`) will immediately resolve the returned promise, instead of when the response is received, however I do not think this promise result is …

fix: Add reachability request timeout to improve handling of bad network connections

---

src/internal/internetReachability.ts

This PR aims to fix an issue where `Promise.prototype.finally` is not available. While many platforms have native implementations available for this method, some libraries (probably targeting the web) appear to provide a polyfill for `Promise` regardless of any existing implementations (e.g. storybookjs/react-native#20). As it's probably easier to work around such issues here, this commit replaces the use of `finally` by a similar `then` construction. This fixes issue #309.
The Jest tests currently fail due to #310, however they pass when rolled back to v5.4.0.
This has also been tested on simulators for iOS 10, 12 and 13.

fix: Remove use of `Promise.prototype.finally` to prevent possible compatibility issues

---

README.md

The mockup setup code in the readme was pointing to a `./jest` folder in the project root, while the `netinfo-mock.js` file is located in the `@react-native-community/netinfo/jest/netinfo-mock.js` directory.
This line was originally created in [this PR](https://github.com/react-native-community/react-native-netinfo/pull/275).

docs: Correct Jest mock import location

---

README.md

The doc guides mocking to `NativeModules.RNCNetInfo`, but it seems not works for me. instead mocking with `jest.mock` to `@react-native-community/netinfo`, it works.

Update the mock binding method on README

---

android/src/main/java/com/reactnativecommunity/netinfo/ConnectivityReceiver.java

The motivation behind this PR is to allow apps to remove ACCESS_WIFI_STATE permission in their app, without the app crashing. We have a case in one of our partner apps where we use netinfo for some network logging, but we don't use all the data collected by netinfo, e.g. wifi data. 
We shouldn't crash because of missing permissions, just reduce the data collected.
Before this change:
AndroidManifest.xml in the Android app
<uses-permission android:name="android.permission.ACCESS_WIFI_STATE" tools:node="remove" />
logcat:
java.lang.SecurityException: WifiService: Neither user 10403 nor current process has android.permission.ACCESS_WIFI_STATE.
at android.os.Parcel.createException(Parcel.java:2088)
at android.os.Parcel.readException(Parcel.java:2056)
at …

Only execute WifiManager.getConnectionInfo if ACCESS_WIFI_STATE is granted

---

README.md

The module factory of `jest.mock()` is not allowed to reference any out-of-scope variables.
Note: This is a precaution to guard against uninitialized mock variables. If it is ensured that the mock is required lazily, variable names prefixed with `mock` (case insensitive) are permitted.

fix(tests): fix the mock variable name

---

README.md
android/src/main/java/com/reactnativecommunity/netinfo/ConnectivityReceiver.java
ios/RNCNetInfo.m
src/internal/defaultConfiguration.web.ts

Added BSSID information to the wifi type.
Implementation is basically the same as for SSID. 
Added in the readme how to test it (together with the SSID example).
Fixes #360

BSSID adition to WIFI type

---

README.md
android/src/main/java/com/reactnativecommunity/netinfo/ConnectivityReceiver.java
src/internal/nativeModule.web.ts
src/internal/types.ts

Added WiFi network frequency to WiFi Network State. [Used Android SDK method description](https://developer.android.com/reference/android/net/wifi/WifiInfo.html#getFrequency()).
Example: for 2.4 GHz networks, the `frequency` will be `2457`.
Unfortunately, iOS does not allow to access a connected WiFi frequency, so the property is missing for iOS
Here is the screenshot of `NetInfo.fetch()` result for Android on 5GHz network:
Here is the screenshot of `NetInfo.fetch()` result for iOS on the same5GHz network.
As I mentioned, the `frequency` property is missing
I've extended the `createDetailsMap` at `ConnectivityReceiver.java`. In case a device uses WiFi, we'll extract the frequency from `WifiInfo`. So you can call `NetInfo.fetch()` on any Android phone and `frequency` has to appear in the …

Add method to read WiFi frequency for Android

---

react-native-netinfo.podspec

Refs #312
This small PR updates the `podspec` file and adds `osx` platform there which fixes Pods installation for the macOS platform:
I have tested the change on the local working copy of `react-native-netinfo`.

fix Pods installation on macOS

---

android/src/main/java/com/reactnativecommunity/netinfo/ConnectivityReceiver.java

Supported version is 16 for Android, but used method is not fitting in this minimum version
Fixes #365
Run it on old Android devices with Android lower than v5 (API 21)

Do not use getFrequency method for Android lower than LOLLIPOP

---

android/src/main/java/com/reactnativecommunity/netinfo/ConnectivityReceiver.java
android/src/main/java/com/reactnativecommunity/netinfo/NetInfoUtils.java

Fixes #353 
Added additional check for permission.
Tested locally

Follow up to "Make the ACCESS_WIFI_STATE permission optional"

---

src/internal/types.ts

While using this package I noticed the `isWifiEnabled` boolean on the `NetInfoState` object for Android only (mentioned in the README [here](https://github.com/react-native-community/react-native-netinfo#netinfostate)), but this was missing from the Typescript definitions.
This PR adds the `isWifiEnabled` boolean to the type (missed from https://github.com/react-native-community/react-native-netinfo/pull/255). 🙂
It has been typed as an optional `boolean` as it is only available on Android.

[fix] Add missing isWifiEnabled type definition

---

react-native-netinfo.podspec

Latest Xcode 12 fails to build while without a module to depend on React-Core directly hence this change is necessary for all native modules on iOS. For more details please check: facebook/react-native#29633 (comment)

React-Core added to podspec for Xcode 12 compatibility

---

windows/RNCNetInfoCPP/RNCNetInfoCPP.vcxproj

Fix error produced when module is added to a React Native app and run in Windows emulator.
Error reads: "The target "Deploy" does not exist in the project".
Create a React Native Windows app.
Add datetimepicker module to app via `yarn add`.
Run `npx react-native run-windows`.
If app deploys successfully and loads in the Windows emulator, the code change has succeeded.

Resolve Missing Deploy Target for Windows

---

android/build.gradle

Hi 👋
Here is a small proposal of fixing a version of `androidx.core:core` artifact used in this project.
Currently the `com.reactnativecommunity:netinfo:5.9.6` artifact is published with dynamic version for the `androidx.core:core` artifact.
This causes silently putting the latest, less stable alpha versions of `androidx.core:core` to be pulled transitively, unless this is suppressed or overriden everywhere in the project.
Example output of Gradle dependencies resolution:
```
|    +--- com.reactnativecommunity:netinfo:5.9.6
|    |    \--- androidx.core:core:1.+ -> 1.5.0-alpha04 (*)
```
It can be definitely fixed from the consumers side of the `com.reactnativecommunity:netinfo` artifact, but I believe more consumers of your library might have similar problem of silently depending on alpha …

Use androidx.core:core:1.3.2 instead of dynamic 1.+ version

---

ios/RNCNetInfo.m

The way that telephony was imported broke builds for catalyst, this imports the 2/4 specific files that are used in CoreTelephony.

Support Mac Catalyst

---

README.md
src/index.ts
src/internal/internetReachability.ts
src/internal/nativeModule.web.ts
src/internal/types.ts

The hook [`useNetInfo` ](https://github.com/react-native-netinfo/react-native-netinfo#usenetinfo) returns the [NetInfoState](https://github.com/react-native-netinfo/react-native-netinfo/blob/master/README.md#netinfostate).
On the first initial call some state values are still unknown. 
Therefore the **type** `unknown` is defined in the initial NetInfoState in this hook.
=> See [docs here](https://github.com/react-native-netinfo/react-native-netinfo/blob/master/README.md#netinfostatetype)
=> See [code here](https://github.com/react-native-netinfo/react-native-netinfo/blob/master/src/index.ts#L98)
However, the NetInfoState values `isConnected` and `isInternetReachable` are already defined as `false` within the initial state even though their actual values have not been determined yet (=> …

fix(useNetinfo): do not return false on initial unknown state

---

android/src/main/java/com/reactnativecommunity/netinfo/NetworkCallbackConnectivityReceiver.java

Use registerNetworkCallback instead of registerDefaultNetworkCallback as the default method isn't notified of wifi network changes that are available to the app but not the system / other apps.
When I use react-native-wifi-reborn to [connect](https://github.com/ThanosFisherman/WifiUtils/blob/master/wifiutils/src/main/java/com/thanosfisherman/wifiutils/ConnectorUtils.java#L377) with an IoT wifi network (for commissioning), and I use `fetch`, netinfo returns the correct network information. However the `isConnected` is `false` and the eventListener isn't notified of the change.
After debugging the code I noticed that the [ConnectivityNetworkCallback](https://github.com/react-native-netinfo/react-native-netinfo/blob/master/android/src/main/java/com/reactnativecommunity/netinfo/NetworkCallback …

fix(android): isConnected is wrong incorrect for wifi networks only the app has access to

---

jest/netinfo-mock.js

Changed the mocked return for the `useNetInfo` to return direct state instead of promise<state>
* Right now: see if any breaks.. 
Fixes #514
* This might break someone tests when they update this package.. so its a minor update perhaps?

fix(jest): mock return value not resolve value for useNetInfo mock

---

android/build.gradle

Fixes an issue when building and running instrumented tests (e.g. Detox) for a React Native project on Android, the following build error was occurring:
```
Execution failed for task ':react-native-community_netinfo:mergeExtDexDebugAndroidTest'.
> Could not resolve all files for configuration ':react-native-community_netinfo:debugAndroidTestRuntimeClasspath'.
> Failed to transform core-1.6.0-alpha03.aar (androidx.core:core:1.6.0-alpha03) to match attributes {artifactType=android-dex, dexing-enable-desugaring=false, dexing-is-debuggable=true, dexing-min-sdk=23, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-runtime}.
```
If an Android library uses Java 8 language features then it must …

Fix assembleAndroidTest builds

---

android/gradle.properties
android/src/main/java/com/reactnativecommunity/netinfo/types/CellularGeneration.java
ios/RNCConnectionState.h
ios/RNCConnectionState.m
src/__tests__/fetch.spec.ts
src/internal/types.ts

Adds support for the 5G cellular type on Android and iOS. Intentionally missing Windows changes because the native platform does not have a 5G type yet according to the documentation that @matt-oakes shared in issue #153
JS changes
- Add the 5G enum type
- Add unit tests
Android changes
- Bump compile sdk version to 29 and bump platform tools version to latest 29 to match (required to get access to new enum)
- 
Blocked on testing. Looking for help from others testing these changes.
I ran into multiple issues building the app on iOS and Android.
For now, I'm just going to open a PR and see if the CI pipeline can validate my changes, because I can't build this project even from the master branch.
On iOS, I get the following build error when building the example iOS app.
```
luis@MacBook-Pro …
```

[feat] Add 5g cellular type

---

package.json
react-native.config.js

without this the example won't run on non-windows platforms
Silly Windows coders ;-) @tero-paananen / @jonthysell (I kid, this is the exact sort of error I make in the other direction)
Related #521 / https://github.com/react-native-netinfo/react-native-netinfo/pull/521/files#diff-8be869fd4628b75fa5a2b47a309cc53741d78a47478966dc3e4b3c50ffce00d9 
`yarn && yarn ios` should work on a macOS machine
Hopefully Tero or Jon can give it a look to make sure I haven't made it work on macOS but busted it for Windows

test(example): use cross-platform path style

---

android/src/main/java/com/reactnativecommunity/netinfo/ConnectivityReceiver.java
android/src/main/java/com/reactnativecommunity/netinfo/NetworkCallbackConnectivityReceiver.java

This allows brown-field or mixed react-native/native apps to call netinfo
APIs and update the connectivity map etc
Not really testable but i have a work app that uses these interfaces on the native side, and they simply don't compile without these changes

feat(android, native): make native API public for mixed-native use

---

ios/RNCConnectionState.m

While I was working in the module I saw the warning that we were touching symbols only available on iOS14.1 with no guard, that will crash on older iOS
Ask for testers from #436 and #417

fix(ios, 5g): do not use 5g symbols until iOS14.1

---

example/index.tsx

Hello and thank you for creating/maintaining this package.
I'm not a very experienced dev, so please forgive me for any missteps in this PR.
The purpose of this is to fix some jittering I noticed when running the example app on the iOS emulator (see the video below). I also took the liberty of pretty-printing the JSON output for each of the examples, but perhaps this isn't the preference for this project for one reason or another. While setting this up I also bumped the `netinfo` version in the podfile.
I've tested these changes in the iOS, Android and web examples. Below are videos and screenshots of before and after:
**Output without pretty-printing**
**Pretty-printed output**
**Scroll jittering**
**Scroll jittering removed**

style(example): fix scrollview jitter in example app

---

.github/workflows/ci.yml

When I do development I am typically a fork-based workflow, and the publish tries to run when I merge things to the main branch on my fork
This should stop that
I merged it on master branch on my fork and it no longer attempted to deploy https://github.com/mikehardy/react-native-netinfo/actions/runs/1472040957
The final test is that it does run the deploy here when merged (though with a "chore" tag hopefully it does not release...)

chore(release): do not run publish workflow on forks

---

jest/netinfo-mock.js

`NetInfo.addEventListener()` returns `unsubscribe` function from actual api, but corresponding jest mock returns nothing. Jest mock should also return a mocked function.
Dependent on existing test suite

fix(jest, mock): addEventListener mock returns a function to match API

---

README.md
src/internal/nativeModule.web.ts
src/internal/types.ts

Whenever connection type is 'unknown', library returns isConnected=false instead of actual connection state.  Unknown network type does not necessarily mean that we have no internet connection. For instance, Electron apps and apps running on chromebooks with instant tethering enabled return 'unknown' network type even when connected to the internet.
We should return the correct connection state even for 'unknown' connection type
1) Launch app on chromebook with instant tethering enabled
2) Bind change event listeners to the NetworkInformation
3) Verify that isConnected property is present in state returned from the listener and that it indicates actual network state
Fixes #450

fix(web, isConnected): Return actual connection state even if network type is 'unknown'

---

android/src/main/java/com/reactnativecommunity/netinfo/NetworkCallbackConnectivityReceiver.java

Attempt to fix https://github.com/react-native-netinfo/react-native-netinfo/issues/542 and https://github.com/react-native-netinfo/react-native-netinfo/issues/537 without fully undoing https://github.com/react-native-netinfo/react-native-netinfo/pull/510 changes.
The change aims to address the issue https://github.com/react-native-netinfo/react-native-netinfo/pull/510 fixes (not calling the network methods in the callback), but preserving the original implementation that uses data from the callbacks.
Could use some review and thoughts @mikehardy and @Willham12 
Manually tested on a Google Pixel 5 (Android 12)
Commands that helped debug:
adb shell dumpsys deviceidle force-idle
adb shell dumpsys deviceidle unforce
adb shell input keyevent KEYCODE_WAKEUP

fix(android): try async state fetch as stale state workaround

---

android/src/main/java/com/reactnativecommunity/netinfo/NetworkCallbackConnectivityReceiver.java

Make sure we use a final reference to the instance variables in case they are modified in another callback while being used.
Should fix: https://github.com/react-native-netinfo/react-native-netinfo/issues/549
The fix is rather simple, just keep a reference to the value before re-using it all around in the function so another callback changing the instance variables won't cause the null pointer exception nor inconsistencies with a value changed halfway through the call.
Tested on Google Pixel 5 (Android 12) and Pixel 2 (Android 11)

fix(android): use method-local ref to instance var for multi-thread safety #549

---

android/src/main/java/com/reactnativecommunity/netinfo/ConnectivityReceiver.java
android/src/main/java/com/reactnativecommunity/netinfo/NetInfoModule.java

This commit just make sure that module will not  read MAC info before add listener for it.
Everytime createConnectivityEventMap method called when send event, it will get wifiinfo.
It's illegal in China when app read MAC info before user agree the privacy agreement.

fix(android): avoid send event when has no listener

---

android/src/main/java/com/reactnativecommunity/netinfo/NetworkCallbackConnectivityReceiver.java

When the app is started with no connectivity (e.g., wifi off or airplane mode), the library currently reports `unknown` and `connected = true` values because network listeners are never called when there's no network info, so all default values are read.
After this, we now try to properly set the initial network values on register (similar to what the old broadcast received does and was not carried over to the new implementation.
I've also taken the chance to replace the `Runnable` with a lambda as suggested by the linter.
P.S.: no idea why old commits were carried over, I'm sure I branched from master.
Tested on Google Pixel 5 (Android 12, RN 0.66.3)
Steps to test:
- Turn airplane mode on
- Open the app (cold start, no previously stored states)
- Check results of `NetInfo.fetch()` on …

fix: android: make sure initial network value is not stale on app startup

---

android/src/main/java/com/reactnativecommunity/netinfo/NetworkCallbackConnectivityReceiver.java

Addressing issue #554
It was noticed that Android 7 and up when ever the devices airplane mode was enabled then disabled the `isConnected` value would be false even though internet was present. This only happened when the device has both Wifi and LTE enabled and came out of airplane mode. 
After looking into the [onLost](https://developer.android.com/reference/android/net/ConnectivityManager.NetworkCallback#onLosing(android.net.Network,%20int)) method, I switch over to using [registerDefaultNetworkCallback](https://developer.android.com/reference/android/net/ConnectivityManager#registerDefaultNetworkCallback(android.net.ConnectivityManager.NetworkCallback)) for the callback register. This prevent the `onLost` methods from being fired when there was Network access from at least on off the …

Airplane mode bug [Android]

---

android/src/main/java/com/reactnativecommunity/netinfo/ConnectivityReceiver.java

Close: https://github.com/react-native-netinfo/react-native-netinfo/issues/536
Run example on Real Device

feat(android): add ethernet information

---

README.md
example/ConnectionInfoRefresh.tsx
example/index.tsx
jest/netinfo-mock.js
src/index.ts
src/internal/state.ts

Fixes https://github.com/react-native-netinfo/react-native-netinfo/issues/593
This pull request implements a new imperative API called `refresh` to update NetInfo's state by forcing the native interface to recompute the library's internal state. More detailed in the [linked issue](https://github.com/react-native-netinfo/react-native-netinfo/issues/593) 🙂 
Keeping the tests pretty simple for now:
1. Run `yarn start:web` to run the example web app.
1. Open and clear the network console.
1. Tap on `NetInfo.fetch` – observe that no network request is made to retest internet reachability.
1. Tap on `NetInfo.refresh` – observe that a network request is made to retest internet reachability.
There's certainly more that could be done to test this, but personally this is enough to make me confident …

feat: add imperative api to refresh state

---

README.md
windows/RNCNetInfoCPP/RNCNetInfoCPP.vcxproj
windows/RNCNetInfoCPP/packages.config

Changed to general version for WindowsTargetPlatformVersion
Using an explicit version of WindowsTargetPlatformVersion requires that specific windows SDK version to be installed on the machine.
In Visual Studio 2017 (version 15 or build tools 141) and earlier it was required but as of Visual Studio 2019 (v16 or v142) and Visual Studio 2022(v17 or v143) you can simply specify "10.0". This allows a lot more flexibility to the developer or build machine as there is a growing number of different windows 10 SDK out there now.
You can now install/run on machines without needing as specific of a windows 10.0 version (think of this as saying using the latest version of windows 10 sdk you have installed, so long as it meets the WindowsTargetPlatformMinVersion.
Newer versions of azure hosted windows …

fix(windows)!: change WindowsTargetPlatformVersion to 10.0 / drop arm32 / drop rnw < 0.63

---

README.md
src/internal/defaultConfiguration.ts
src/internal/defaultConfiguration.web.ts
src/internal/internetReachability.ts
src/internal/types.ts

While using the API, the reachability checks for some Android devices, namely Amazon Kindle Fires, weren't entirely reliable. Upon testing a case where I manually pulled the plug on the internet, the `isInternetReachable` would still return `true` for minutes without an update. The non-native implementation for reachability checks for iOS works very well, so I'm proposing a solution where the user can specify a param to utilize the custom reachability checks to bypass this issue (or if for whatever other reason, they want to specify custom reachability parameters). 
* Ran `yarn start:android` and built to Amazon Fire Kindle. Accurately reported Network changes
* Tests passed:

feat: add parameter useNativeReachability to optionally choose non-native reachability test

---

README.md
example/android/build.gradle

`androidXCore` is no longer required as it's not used anywhere in the project.
AndroidX dependency was dropped in https://github.com/react-native-netinfo/react-native-netinfo/commit/2569f56

Remove androidXCore requirement

---

jest/netinfo-mock.js

This pull request allows mocking `NetInfoStateType`. And resolves the error below when testing any component uses `NetInfoStateType`.

fix: allow mocking netinfostate type for testing

---

ios/RNCConnectionState.m
ios/RNCNetInfo.m

There have been some issues and PRs on Mac Catalyst support like #392, #412, and #415, and #415 specifically supposed to have added the support, but I was still getting compilation errors like what @giona69 posted in https://github.com/react-native-netinfo/react-native-netinfo/issues/392#issuecomment-803315982.
For each `#if` platform check in `ios/RNCNetInfo.m` and `ios/RNCConnectionState.m`, I also added another condition for `TARGET_OS_MACCATALYST` similar to what was proposed in #412 and now everything compiles and runs.
I have little experience with Objective-C or macOS development, and I have no idea why `CoreTelephony` was not compiling, but the existing implementation with `ifaddrs.h` seems to work perfectly fine for Mac Catalyst.
I modified the …

fix(mac-catalyst): add check for mac catalyst target to support the platform

---

src/internal/state.ts

Related to #591 #557
I've experienced problems with useNetInfo and location permissions. I'm using Android 11 and my app only has location permissions when the app is in foreground.
If the network changes while the app is in background bssid and ssid values are not being reported (or obfuscated). When the app comes back to foreground, no events are being triggered.
To handle that case, I've triggered `NetInfo.refresh()` when the appState becomes active again. However, this doesn't update the useNetInfo state. To force the update, I've added the event dispatch after updating _lastState.
1. Run on a phone with Android 11 (10 I think is the same thing).
2. Add this code to see updates to netInfo.
```js
const netInfo = useNetInfo();
useEffect(() => {
console.log('net info ssid is updated', …
```

notify subscriptions after refresh

---

windows/RNCNetInfoCPP/RNCNetInfo.cpp

Even if not properly documented, some properties of `windows.networking.connectivity.connectionprofile` can throw. It's the case of `NetworkAdapter` since it's then calling `check_hresult` which will throw if the returned hresult is an error one.
Since `RNCNetInfo::getIpAddressSync` is marked as `noexcept`, any exception thrown in this method will call `std::terminate`.
This commit is to return `"unknown"` in this case.
Unfortunately, I wasn't able to reproduce the crash some of our users face myself so I can't validate it fixes it.
Though I imported these changes in our own RN Windows project and made sure IP info is still working in the general case!
For reference, here is the stack trace we get in our crash reporting system:
RNCNetInfoCPP!__GSHandlerCheck_EH4+0x64 …

fix(windows): fix crash in getIpAddressSync

---

android/src/main/java/com/reactnativecommunity/netinfo/ConnectivityReceiver.java

fix(android): return netmask of first IPv4 address

---

src/internal/nativeModule.web.ts

Solving https://github.com/react-native-netinfo/react-native-netinfo/issues/645
Add checks to web version of NetInfo to avoid trying to access properties of `undefined`. This scenario can occur when using this package with Server Side Rendering (SSR).
After adding these, I was able to build the Next.js app.

[Web] Checking `window` before accessing 

---

windows/RNCNetInfoCPP/RNCNetInfo.cpp

Some users are facing this crash: 0xC0000005: Access violation reading location 0x0000000000000000.
When inspecting crash dump, last stack trace in RNCNetInfo is [RNCNetInfo.cpp:62](https://github.com/react-native-netinfo/react-native-netinfo/blob/3e251ab08a4b6d9cbe4709c5fa24dbdfc96eced6/windows/RNCNetInfoCPP/RNCNetInfo.cpp#L62)
These impacted users had LTE network adapter cards marked as `LteAdvanced | Custom` which isn't support by current RNCNetInfo implementation as `dataClass` wasn't treated as an enum supporting flags.
So `nullptr` was assigned to `std::optional<std::string>` and since the optional object is considered initialized when assigning `nullptr` then when dereferencing the value, it led to null pointer exception.
* Use `std::nullopt` instead of `nullptr` for unknown class …

fix(windows): fix crash in GetCellularGeneration for some LTE network adapters

---

android/src/main/java/com/reactnativecommunity/netinfo/ConnectivityReceiver.java

I recently faced a crash on a device that does not have WiFi and not provide the WiFi system service.
```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.net.wifi.WifiManager.isWifiEnabled()' on a null object reference
at com.reactnativecommunity.netinfo.ConnectivityReceiver.createConnectivityEventMap(ConnectivityReceiver.java:138)
at com.reactnativecommunity.netinfo.ConnectivityReceiver.getCurrentState(ConnectivityReceiver.java:83)
at com.reactnativecommunity.netinfo.NetInfoModule.getCurrentState(NetInfoModule.java:58)
.....
```
Only thing we use in our app is
`const { isConnected } = useNetInfo();`
So for us it doesn't really matter what kind of connection, if the device does not support WiFi but has some other connectivity it is fine.
This PR will add …

fix(android): avoid crash on devices without wifi

---

src/internal/nativeModule.web.ts

Fix an issue causing an SSR exception if `getCurrentState` is called.
As things currently stand, if for any reason you end up calling `getCurrentState` during SSR you end up getting an exception due to `navigator` being `undefined`.
1. Call `getCurrentState` during SSR without this change. See you receive an exception.
2. Call `getCurrentState` during SSR _with_ this change. See you _do not_ receive an exception.

fix(web): verify `window` exists before attempting to access navigator

---

android/src/main/java/com/reactnativecommunity/netinfo/NetworkCallbackConnectivityReceiver.java

We are submitting this PR as part of the errors we are seeing in one of our hostapps in Microsoft on Android. Especially on Android 11, there seems to be a SecurityException thrown if the app is not bound yet while the Activity is created. Google has fixed this issue in vNext, Android 13 and Android 12. However, Android 11 still remains unpatched crashing around 500 times per week.
For the test plan, it is a bit hard to repro due to the timing error. If you have a look at the fix by Chalard Jean at Google [here](https://android.googlesource.com/platform/frameworks/base/+/249be21013e389837f5b2beb7d36890b25ecfaaf%5E%21/), it involves several manual steps to get into this bad state for the ConnectivityManager.
https://github.com/react-native-netinfo/react-native-netinfo/issues/674

fix: do not crash on android 11

---

android/build.gradle

Follow-up from https://github.com/react-native-netinfo/react-native-netinfo/pull/675. This ensure proper backwards-compability to older react-native and gradle versions.

fix(android): making rn >= 73 support also compatible with rn <= 66

---

src/internal/types.ts

When using NetInfo.addEventListener was getting `isWifiEnabled` in data but was getting typeerror when using it. so add `isWifiEnabled` as `boolean` and optional type in NetInfoUnknownState and NetInfoDisconnectedState.
1] Run Yarn test got all my the test cases passed.
2] Run yarn validate:typescript all test case passed without any error.

Fixed Typeerror for addvenetlistner added isWifiEnabled type in NetInfoUnknownState and NetInfoDisconnectedState

---

.github/workflows/ci.yml
README.md
src/internal/internetReachability.ts

Taken from https://github.com/react-native-netinfo/react-native-netinfo/issues/439#issue-787487438

fix!: cancel _checkInternetReachability request on timeout & cancel via AbortController

---

android/gradle.properties
android/src/main/java/com/reactnativecommunity/netinfo/AmazonFireDeviceConnectivityPoller.java
android/src/main/java/com/reactnativecommunity/netinfo/BroadcastReceiverConnectivityReceiver.java
android/src/main/java/com/reactnativecommunity/netinfo/NetInfoUtils.java

This PR introduces Android targetSdk 34 (Android 14) support.
Without this PR, devices running Android 14 will crash if the app using this dependency is using `targetSdk=34`.
An alternative approach would be to directly include `androidx.core:core` as a dependency of this project and use `ContextCompat.registerReceiver` instead.
More information can be found in this issue: https://github.com/react-native-netinfo/react-native-netinfo/issues/681
This is the smallest change that I can make and have this work, I think. Locally, in order to get this to build on my machine, I did also need to upgrade the gradle wrapper to work with newer JDKs. But I don't think those changes are necessary for this PR. We'll see what CI says :P

feat(android)!: specify export mode on BroadcastReceivers, requires compileSdk 33+

---

README.md
src/index.ts

The objective here is to allow consumption of this library without the global singleton. I am currently experiencing a bug where this library is continuing to check the network status in the background and then when my app comes back into foreground and I retrieve the state from netinfo, it's saying there's no connection. This is because the netinfo singleton is running in the background and the network request eventually gets blocked by iOS. see issue [Issue #669](https://github.com/react-native-netinfo/react-native-netinfo/issues/669). It would be nice to pause checking the status when ever my app goes into the background. ie `useNetInfo({isPaused: true})`. It would nice for all network checking to stop if `useNetInfo` is unmounted.
This library manages a singleton which is beneficial …

feat: add useNetInfoInstance - a non singleton-state hook to manage configs / events independently

---

src/internal/internetReachability.ts

AbortController.abort() throws DOMException with name AbortError. This exception rejects promise with reason declared in abort function attribute as I described at https://github.com/react-native-netinfo/react-native-netinfo/issues/699

fixed abort pending request of internetReachability

---

src/internal/nativeModule.web.ts

Web applications at Tizen use Chromium. And in the latest versions of Tizen seems being a support of Network Information API. I tasted react-native-netinfo at Tizen TV device and emulator. The event 'change' fired only at application start. If the connection is lost, the TV displays a native warning, but the event in Web application is not fired.
Firstly I found at Tizen docs guide to get information about network using [tizen API](https://docs.tizen.org/application/web/guides/device/system-information/). But then I came across an official guide for Web apps where 'online' / 'offline' are used to watch network connection changes.
So I decided to make an additional check for Tizen to solve this problem. Now web application fires events on connection changes at Tizen TV device and emulator. …

added support for Tizen and WebOS

---

src/internal/internetReachability.ts

New solution for fetch abort with 'Cancel' promise as before (for browsers without full support of AbortController API).
Initiated after discussion with [Tymofiev](https://github.com/Tymofiev) in #700

updated internetReachability fetch abort

---

src/internal/internetReachability.ts

Fixed fetch abort when timeout is out. Added reject to timeout instead of controller.abort() for browsers unsupported AbortController

fixed fetch abort on timedout

---

ios/RNCConnectionState.m
ios/RNCNetInfo.m
react-native-netinfo.podspec

This PR adds support for [React Native visionOS](https://github.com/callstack/react-native-visionos), the new out-of-tree platform.
VisionOS also does not support the `CoreTelephony` API, so it's just a matter of adding extra checks for `TARGET_OS_VISION` where we already have checking for other platforms such as `TARGET_OS_TV`, `TARGET_OS_OSX` and `TARGET_OS_MACCATALYST`.
- `yarn test`: all tests still pass
- `yarn start:ios` and `yarn start:macos`: all platforms still build with no issues.
<details>
<summary>iOS</summary>
</details>
<details>
<summary>macOS</summary>
</details>

feat: add visionOS support

---

src/internal/nativeInterface.ts

When trying to use `react-native-netinfo` with the new architecture and bridgeless mode on (react-native version 0.74.0-nightly-20240123-cbd818dad), the user is faced with an unhandled promise rejection 
----
This error happens because of the following code inside nativeInterface.ts
https://github.com/react-native-netinfo/react-native-netinfo/blob/94c5398a3debad44190ba1f71f766401b424ebfe/src/internal/nativeInterface.ts#L31-L38
Currently we cannot use the spread operator directly on the object returned from React Native's NativeModules, given that the module object is a host object. So to fix that we should use `Object.assign` instead or directly use `NativeModules.RNCNetInfo`
After this change everything works as expected and the compatibility layer allows `react-native-netinfo` to be …

fix: update nativeInterface default export to support bridgeless mode

---

README.md

No Big change but There was a grammar mistake in the README.md
> then change you imports from
so I change it to
> then change your imports from
I noticed this mistake in `npm` package page.

docs(README): change 'you' to 'your'

---

android/build.gradle

Monorepos are configured and structured on what works best for the project. Since this can vary from project to project, having a dynamic way to find dependencies will make this work for more projects. Currently, the repo only supports certain configurations of Monorepo structures. This PR adopts a similar approach as Expo to locate the react native package within the project. [Expo usage for reference]( https://github.com/expo/expo/blob/9821f2f8c8927d930a15041f22cd55e28f443274/packages/expo-modules-core/README.md?plain=1#L65)
This PR also falls back to the original functionality if the package cannot be resolved by node.
1. `yarn`
2. `yarn start`
3. `yarn start:android`
4. Put in a `println` statement to see what `$reactNativePackage.parentFile` is on the next build to see it working.
5. …

build: Use node resolver to find react native package directory

---

example/ConnectionInfoRefresh.tsx
src/index.ts

We use react-native-netinfo in our app and encountered an issue with the library sending multiple reachability requests in parallel. 
This PR adds isRequestInProgress to track whether a reachability request is currently in progress, preventing multiple parallel requests.
Additionally, it implements proper cleanup of listeners in useEffect to prevent multiple listeners from being active simultaneously.
1. Run the example app
2. Tap the "Tap to trigger multiple refreshes" button
3. Observe that subsequent refresh calls were prevented due to an ongoing requests
https://github.com/react-native-netinfo/react-native-netinfo/assets/19835085/2b549688-783b-4914-8fb9-624a99653d9e

fix: ensure one reachability check in-flight at once / proper useEffect listener cleanup
